spring.application.name=productos

# Conexión a DB
spring.datasource.url=jdbc:postgresql://localhost:5432/bdtf
spring.datasource.username=postgres
spring.datasource.password=rckolv

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Es buena práctica especificar el dialecto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto de Spring Boot
server.port=8080

# --- Configuración de JWT ---
# Una clave secreta MUY larga y aleatoria (puedes generar una online)
jwt.secret=masterservproductosclaveultrasecreta1234567890
# Tiempo de expiración del token en milisegundos (aquí 1 día)
jwt.expiration=86400000


logging.level.org.springframework.security=DEBUG